# @package _global_

defaults:
  - override /data: ttt_dynamic_carrier_slow100_observe10_2cam
  - override /model: fastwam
  - _self_

batch_size: 4
num_workers: 4
gradient_accumulation_steps: 1

model:
  mot_checkpoint_mixed_attn: true
  skip_dit_load_from_pretrain: true
  action_dit_pretrained_path: null
  video_ttt:
    enabled: true
    observation_training: true
    w0_training: false
    train_backbone: false
    train_residual_gate: true
    num_tries: 1
    switch_chunks: false
    num_layers: 8
    layer_indices: null
    rank: 192
    mini_batch_size: 64
    ttt_lr: 0.5
    inner_update_mode: scan
    scan_kernel: triton
    observe_prefill_group_size: 10
    execution_backward_group_size: 2
    use_global_rope: true
    time_stride: 2
    include_context_tokens: true
    state_token_count: 1
    residual_gate_init: 0.0
    residual_gate_override: null
  loss:
    lambda_video: 1.0
    lambda_action: 1.0
    lambda_video_ttt: 0.0

lr_scheduler_type: "cosine"
learning_rate: 2.0e-4
num_epochs: 1
max_steps: 30000
log_every: 5
save_every: 1000
keep_last_checkpoints: 2
eval_every: 0
eval_num_inference_steps: 10

weight_decay: 1.0e-2
resume: null

wandb:
  enabled: false
  name: ttt_dynamic_carrier_slow100_observe_ttt_2cam224_video_ttt
